CO = '[Corporation name] inc.'
NAME = '[Your full name]'
EMAIL = 'shersahray@outlook.com'
ADDR = '[mailing address]'

PRIVACY_EN = [
 ('h2', '1. Who we are'),
 ('p', f'Sumlora is accounting software made by {CO}, a corporation incorporated in Quebec (“we”, “us”). This policy explains what personal information we handle when you use Sumlora, why, and what choices you have.'),
 ('p', f'Our person in charge of the protection of personal information (privacy officer) is {NAME}. You can reach them at {EMAIL} or {ADDR}.'),
 ('h2', '2. Two ways Sumlora runs, and what that means for your data'),
 ('ul', ['**On your own computer or your own server.** Your books stay on your computer or your server. We do not receive them, see them or store them. This policy then covers only the little we receive from you directly, such as your name and email when you buy a licence or write to us.',
         '**Hosted by us.** Your books are stored on servers we rent from Microsoft Azure in Canada. We hold that information on your behalf, under this policy and, for firms, the Data agreement for firms.']),
 ('h2', '3. What we collect'),
 ('table', ['What', 'Examples', 'Why we need it'], [
   ['Account details', 'Name, email address, username, firm name, role', 'To create your account, sign you in and contact you about it'],
   ['Sign-in security', 'Your password (stored only in scrambled form, never readable), two-step sign-in settings, sign-in times and the IP address used', 'To keep accounts secure and spot sign-ins that aren’t yours'],
   ['Your agreement to these terms', 'Which version you agreed to, when, and the IP address used', 'To show who agreed to what'],
   ['Billing details', 'Subscription plan, invoices, payment status', 'To bill your monthly subscription. Card numbers are handled by our payment provider; we never see them.'],
   ['Your books', 'Transactions, invoices, bills, customers, vendors, bank lines, receipts and attachments', 'To provide the accounting service you asked for'],
   ['Payroll records, if you use payroll', 'Employees’ names, addresses, social insurance numbers, pay and deductions', 'To calculate pay, deductions, T4, RL-1 and records of employment'],
   ['Activity log', 'Who changed what, and when', 'So your firm can see the history of its books, and to investigate problems'],
   ['Support messages', 'What you write to us', 'To answer you']]),
 ('p', 'Your books may contain personal information about other people, such as your customers, vendors and employees. When you use Sumlora, you confirm you are allowed to record that information in it.'),
 ('p', 'We do not sell personal information. We do not use your books for advertising. We do not track you across other websites.'),
 ('h2', '4. Where your information is stored'),
 ('p', 'When we host Sumlora for you, your books, attachments and backups are stored in Canada, in Microsoft Azure’s Canada East region (Quebec City). A copy of each day’s backup is kept in separate Azure storage in Canada, so one problem cannot destroy both.'),
 ('p', 'Some features send information outside Quebec or outside Canada, as the next section explains. Before any such transfer, we assess whether the information will be adequately protected, as Quebec law requires.'),
 ('h2', '5. Who we share it with'),
 ('p', 'We share personal information only with the service providers below, only what each needs, and only to run Sumlora. Each is bound by a contract to protect it.'),
 ('table', ['Provider', 'What they receive', 'Where', 'When'], [
   ['Microsoft (Azure)', 'Everything stored in hosted Sumlora', 'Canada', 'Always, for hosted accounts'],
   ['Anthropic PBC (maker of Claude)', 'For receipt reading: the receipt or bill image. For bank suggestions: bank line dates, descriptions and amounts, payee names and the chart of accounts.', 'United States', 'Only when AI features are turned on for a company and someone uses them. Anthropic’s commercial terms say it does not train its models on this data.'],
   ['Stripe', 'The invoice number, amount and customer name for an online payment link. Your customer types their card details on Stripe’s page, not in Sumlora.', 'Canada and United States', 'Only when a company turns on online payments'],
   ['Plaid', 'The bank sign-in happens in Plaid’s own window; Sumlora never sees the bank password. Plaid sends Sumlora the bank’s account names, the last digits of each account number, and their transactions (date, amount, description).', 'Canada and United States', 'Only when someone in your firm connects a bank feed for a company. Disconnecting it stops it.'],
   ['Your own email provider (for example Microsoft 365 or Gmail)', 'Invoices and statements you choose to email, sent from your own mailbox', 'Depends on your provider', 'Only when you connect your mailbox and send email'],
   ['GitHub (Microsoft)', 'Your IP address when the desktop app checks for an update', 'United States', 'When the desktop app checks for updates']]),
 ('p', 'AI features (receipt reading and bank suggestions) are off until someone in your firm turns them on for a company. If you turn them on, what you ask the AI to read leaves Canada. You can turn them off at any time.'),
 ('p', 'We will also share information if the law requires it, for example a court order. When the law allows, we will tell you first.'),
 ('p', 'If we sell or merge our business, your information may pass to the new owner, who must keep protecting it under this policy. We will tell you before it happens.'),
 ('h2', '6. How we keep it safe'),
 ('ul', ['Connections to Sumlora are encrypted (HTTPS), and Azure encrypts the stored data.',
         'Passwords are stored only in scrambled (hashed) form. Five wrong passwords lock an account for 15 minutes.',
         'Two-step sign-in is available for every user, and we require it on our hosted service.',
         'Each user sees only the companies and features their role allows. Clients see only their own company.',
         'Every change to the books is recorded in an activity log.',
         'Backups are made every day and kept in a separate storage location in Canada.',
         f'Only {NAME} and staff who need it to run the service can reach the servers, and they are bound by confidentiality.']),
 ('h2', '7. How long we keep it'),
 ('ul', ['**While your subscription is active:** we keep your books and account for as long as you use Sumlora.',
         '**After you cancel:** you have [60] days to download your books (the year-end package or a backup). We then delete them from our servers.',
         '**Backups:** deleted books disappear from backups within [30] days, as old backups expire.',
         '**Billing records:** kept for 6 years, because tax law requires it.']),
 ('h2', '8. Your rights'),
 ('p', 'You can ask us to:'),
 ('ul', ['tell you what personal information we hold about you, and give you a copy, including in a commonly used format you can take elsewhere;',
         'correct information that is wrong or incomplete;',
         'stop using or delete information we no longer need, or withdraw your consent, subject to legal and contract limits;',
         'explain how we handle your information.']),
 ('p', f'Write to our privacy officer at {EMAIL}. We answer within 30 days. If your information is in books a firm keeps for you, we will pass your request to that firm, because they decide what happens to it.'),
 ('p', 'If you are not satisfied with our answer, you can complain to the Commission d’accès à l’information du Québec or the Office of the Privacy Commissioner of Canada.'),
 ('h2', '9. If something goes wrong'),
 ('p', 'If a confidentiality incident (a data breach) happens, we record it in our incident register and act quickly to limit the harm. If it creates a risk of serious injury, we tell the affected people and the Commission d’accès à l’information du Québec, and the Office of the Privacy Commissioner of Canada where federal law applies. For data a firm keeps in Sumlora, we tell that firm right away so it can meet its own duties.'),
 ('h2', '10. Changes to this policy'),
 ('p', 'We will post any change here with a new effective date. For a significant change, we will tell you by email or in Sumlora at least 30 days before it applies, and ask you to agree again when you next sign in.'),
 ('h2', '11. Contact'),
 ('p', f'{NAME}, privacy officer, {CO} · {EMAIL} · {ADDR}'),
]

PRIVACY_FR = [
 ('h2', '1. Qui nous sommes'),
 ('p', f'Sumlora est un logiciel de comptabilité conçu par {CO}, une société constituée au Québec (« nous »). Cette politique explique quels renseignements personnels nous traitons quand vous utilisez Sumlora, pourquoi, et quels choix vous avez.'),
 ('p', f'La personne responsable de la protection des renseignements personnels est {NAME}. Vous pouvez la joindre à {EMAIL} ou au {ADDR}.'),
 ('h2', '2. Deux façons d’utiliser Sumlora, et ce que cela signifie pour vos données'),
 ('ul', ['**Sur votre propre ordinateur ou votre propre serveur.** Vos livres restent sur votre ordinateur ou votre serveur. Nous ne les recevons pas, ne les voyons pas et ne les conservons pas. Cette politique ne vise alors que le peu que vous nous transmettez directement, comme votre nom et votre courriel quand vous achetez une licence ou nous écrivez.',
         '**Hébergé par nous.** Vos livres sont conservés sur des serveurs que nous louons à Microsoft Azure au Canada. Nous détenons ces renseignements pour votre compte, selon cette politique et, pour les cabinets, l’Entente sur les données pour les cabinets.']),
 ('h2', '3. Ce que nous recueillons'),
 ('table', ['Quoi', 'Exemples', 'Pourquoi nous en avons besoin'], [
   ['Renseignements de compte', 'Nom, adresse courriel, nom d’utilisateur, nom du cabinet, rôle', 'Pour créer votre compte, vous connecter et communiquer avec vous à son sujet'],
   ['Sécurité de connexion', 'Votre mot de passe (conservé seulement sous forme chiffrée, jamais lisible), réglages de la validation en deux étapes, heures de connexion et adresse IP utilisée', 'Pour protéger les comptes et repérer les connexions qui ne sont pas les vôtres'],
   ['Votre acceptation de ces conditions', 'La version acceptée, quand, et l’adresse IP utilisée', 'Pour démontrer qui a accepté quoi'],
   ['Renseignements de facturation', 'Forfait, factures, état des paiements', 'Pour facturer votre abonnement mensuel. Les numéros de carte sont traités par notre fournisseur de paiement; nous ne les voyons jamais.'],
   ['Vos livres', 'Opérations, factures clients et fournisseurs, clients, fournisseurs, lignes bancaires, reçus et pièces jointes', 'Pour fournir le service de comptabilité demandé'],
   ['Dossiers de paie, si vous utilisez la paie', 'Noms, adresses et numéros d’assurance sociale des employés, salaires et retenues', 'Pour calculer la paie, les retenues, les T4, les relevés 1 et les relevés d’emploi'],
   ['Journal d’activité', 'Qui a modifié quoi, et quand', 'Pour que votre cabinet voie l’historique de ses livres, et pour enquêter sur les problèmes'],
   ['Messages au soutien', 'Ce que vous nous écrivez', 'Pour vous répondre']]),
 ('p', 'Vos livres peuvent contenir des renseignements personnels sur d’autres personnes, comme vos clients, fournisseurs et employés. En utilisant Sumlora, vous confirmez être autorisé à y inscrire ces renseignements.'),
 ('p', 'Nous ne vendons pas de renseignements personnels. Nous n’utilisons pas vos livres à des fins publicitaires. Nous ne vous suivons pas sur d’autres sites Web.'),
 ('h2', '4. Où vos renseignements sont conservés'),
 ('p', 'Quand nous hébergeons Sumlora pour vous, vos livres, pièces jointes et sauvegardes sont conservés au Canada, dans la région Canada Est de Microsoft Azure (Québec). Une copie de la sauvegarde de chaque jour est gardée dans un stockage Azure distinct au Canada, pour qu’un seul problème ne puisse détruire les deux.'),
 ('p', 'Certaines fonctions transmettent des renseignements à l’extérieur du Québec ou du Canada, comme l’explique la section suivante. Avant un tel transfert, nous évaluons si les renseignements bénéficieront d’une protection adéquate, comme l’exige la loi québécoise.'),
 ('h2', '5. Avec qui nous les communiquons'),
 ('p', 'Nous communiquons des renseignements personnels seulement aux fournisseurs de services ci-dessous, seulement ce dont chacun a besoin, et seulement pour faire fonctionner Sumlora. Chacun est tenu par contrat de les protéger.'),
 ('table', ['Fournisseur', 'Ce qu’il reçoit', 'Où', 'Quand'], [
   ['Microsoft (Azure)', 'Tout ce qui est conservé dans Sumlora hébergé', 'Canada', 'Toujours, pour les comptes hébergés'],
   ['Anthropic PBC (créateur de Claude)', 'Pour la lecture des reçus : l’image du reçu ou de la facture. Pour les suggestions bancaires : la date, la description et le montant des lignes bancaires, les noms des bénéficiaires et le plan comptable.', 'États-Unis', 'Seulement quand les fonctions d’IA sont activées pour une entreprise et que quelqu’un les utilise. Selon ses conditions commerciales, Anthropic n’entraîne pas ses modèles avec ces données.'],
   ['Stripe', 'Le numéro, le montant et le nom du client d’une facture, pour un lien de paiement en ligne. Votre client saisit sa carte sur la page de Stripe, pas dans Sumlora.', 'Canada et États-Unis', 'Seulement quand une entreprise active les paiements en ligne'],
   ['Plaid', 'La connexion à la banque se fait dans la fenêtre de Plaid; Sumlora ne voit jamais le mot de passe bancaire. Plaid transmet à Sumlora le nom des comptes, les derniers chiffres de chaque numéro de compte et leurs opérations (date, montant, description).', 'Canada et États-Unis', 'Seulement quand quelqu’un de votre cabinet connecte un flux bancaire pour une entreprise. Le déconnecter y met fin.'],
   ['Votre propre fournisseur de courriel (par exemple Microsoft 365 ou Gmail)', 'Les factures et relevés que vous choisissez d’envoyer, depuis votre propre boîte', 'Selon votre fournisseur', 'Seulement quand vous connectez votre boîte et envoyez un courriel'],
   ['GitHub (Microsoft)', 'Votre adresse IP quand l’application de bureau vérifie les mises à jour', 'États-Unis', 'Quand l’application de bureau vérifie les mises à jour']]),
 ('p', 'Les fonctions d’IA (lecture des reçus et suggestions bancaires) sont désactivées jusqu’à ce que quelqu’un de votre cabinet les active pour une entreprise. Si vous les activez, ce que vous demandez à l’IA de lire quitte le Canada. Vous pouvez les désactiver en tout temps.'),
 ('p', 'Nous communiquerons aussi des renseignements si la loi l’exige, par exemple sur ordonnance d’un tribunal. Quand la loi le permet, nous vous en avertirons d’abord.'),
 ('p', 'Si nous vendons notre entreprise ou fusionnons, vos renseignements peuvent passer au nouveau propriétaire, qui devra continuer de les protéger selon cette politique. Nous vous en avertirons avant.'),
 ('h2', '6. Comment nous les protégeons'),
 ('ul', ['Les connexions à Sumlora sont chiffrées (HTTPS), et Azure chiffre les données conservées.',
         'Les mots de passe sont conservés seulement sous forme chiffrée (hachée). Cinq mauvais mots de passe bloquent un compte pendant 15 minutes.',
         'La validation en deux étapes est offerte à chaque utilisateur, et nous l’exigeons sur notre service hébergé.',
         'Chaque utilisateur ne voit que les entreprises et fonctions que son rôle permet. Les clients ne voient que leur propre entreprise.',
         'Chaque modification des livres est inscrite dans un journal d’activité.',
         'Des sauvegardes sont faites chaque jour et gardées dans un stockage distinct au Canada.',
         f'Seuls {NAME} et le personnel qui en a besoin pour faire fonctionner le service peuvent accéder aux serveurs, et ils sont tenus à la confidentialité.']),
 ('h2', '7. Combien de temps nous les conservons'),
 ('ul', ['**Pendant votre abonnement :** nous conservons vos livres et votre compte tant que vous utilisez Sumlora.',
         '**Après une résiliation :** vous avez [60] jours pour télécharger vos livres (le dossier de fin d’exercice ou une sauvegarde). Nous les supprimons ensuite de nos serveurs.',
         '**Sauvegardes :** les livres supprimés disparaissent des sauvegardes dans un délai de [30] jours, à mesure que les anciennes sauvegardes expirent.',
         '**Dossiers de facturation :** conservés 6 ans, comme l’exigent les lois fiscales.']),
 ('h2', '8. Vos droits'),
 ('p', 'Vous pouvez nous demander :'),
 ('ul', ['de vous dire quels renseignements personnels nous détenons sur vous, et de vous en remettre une copie, y compris dans un format courant que vous pouvez utiliser ailleurs;',
         'de corriger des renseignements inexacts ou incomplets;',
         'de cesser d’utiliser ou de supprimer des renseignements dont nous n’avons plus besoin, ou de retirer votre consentement, sous réserve des limites légales et contractuelles;',
         'de vous expliquer comment nous traitons vos renseignements.']),
 ('p', f'Écrivez à la personne responsable de la protection des renseignements personnels à {EMAIL}. Nous répondons dans un délai de 30 jours. Si vos renseignements se trouvent dans des livres qu’un cabinet tient pour vous, nous transmettrons votre demande à ce cabinet, car c’est lui qui en décide.'),
 ('p', 'Si notre réponse ne vous satisfait pas, vous pouvez porter plainte à la Commission d’accès à l’information du Québec ou au Commissariat à la protection de la vie privée du Canada.'),
 ('h2', '9. En cas de problème'),
 ('p', 'Si un incident de confidentialité (une fuite de données) survient, nous l’inscrivons dans notre registre des incidents et agissons rapidement pour limiter le préjudice. S’il présente un risque de préjudice sérieux, nous avisons les personnes concernées et la Commission d’accès à l’information du Québec, ainsi que le Commissariat à la protection de la vie privée du Canada lorsque la loi fédérale s’applique. Pour les données qu’un cabinet conserve dans Sumlora, nous avisons ce cabinet immédiatement pour qu’il puisse remplir ses propres obligations.'),
 ('h2', '10. Modifications de cette politique'),
 ('p', 'Nous publierons toute modification ici avec une nouvelle date d’entrée en vigueur. Pour une modification importante, nous vous en avertirons par courriel ou dans Sumlora au moins 30 jours avant son entrée en vigueur, et vous demanderons de l’accepter de nouveau à votre prochaine connexion.'),
 ('h2', '11. Pour nous joindre'),
 ('p', f'{NAME}, responsable de la protection des renseignements personnels, {CO} · {EMAIL} · {ADDR}'),
]

TERMS_EN = [
 ('p', f'These terms are an agreement between {CO}, a corporation incorporated in Quebec (“we”, “us”), and the business or firm that signs up for Sumlora (“you”). By creating an account or using Sumlora, you accept them on behalf of your business. Sumlora is sold to businesses, not to consumers for personal use.'),
 ('h2', '1. Your account'),
 ('ul', ['You must give true information when you sign up and keep it up to date.',
         'You decide who in your business gets a user, and what role each has. You are responsible for what your users do in Sumlora.',
         f'Keep passwords private and use two-step sign-in. Tell us right away at {EMAIL} if you think someone else got into your account.',
         'When you invite a client to see their own books, you are responsible for inviting the right person.']),
 ('h2', '2. Your subscription'),
 ('ul', ['Sumlora is billed **monthly, in advance**, in Canadian dollars, at the price for your plan shown when you sign up. GST/HST and QST are added where they apply.',
         'Your subscription renews each month until you cancel.',
         'We may change prices. We will tell you at least 30 days before, and the new price applies from your next month after that notice.',
         'If a payment fails, we will tell you and try again. If it is still unpaid after [14] days, we may limit your account to read-only until it is paid. Your data is not deleted for non-payment until the end of the period in section 11.']),
 ('h2', '3. Cancelling'),
 ('ul', ['You can cancel at any time, from your account or by writing to us. The cancellation takes effect at the end of the month you have already paid for.',
         '[We do not refund partial months.] You keep full access until the end of that month.',
         'Before or after you cancel, download your books with the year-end package or a backup. See section 11 for how long we keep them.']),
 ('h2', '4. Desktop licence codes'),
 ('p', 'If you run Sumlora on your own computer, a licence code activates it. A code is for the business it was issued to. Don’t share it outside your business or try to get around it.'),
 ('h2', '5. Your data'),
 ('ul', ['**Your books belong to you** (or to your client, if you are a firm keeping their books). We do not own them and use them only to provide Sumlora to you.',
         'You can download your books at any time, with a backup or the year-end package.',
         'When we host Sumlora, we back it up every day. Still keep your own copies of important records: tax law requires you to keep your books for at least 6 years.',
         'Our [[Privacy policy|privacy.html]] explains how we handle personal information. For firms, the [[Data agreement for firms|data-agreement.html]] also applies and forms part of these terms.']),
 ('h2', '6. AI features and bank feeds'),
 ('ul', ['Sumlora can read receipts and bills, and suggest categories for bank lines, using Anthropic’s Claude AI. These features are off until you turn them on for a company. When they are on, what you ask the AI to read is sent to Anthropic in the United States, as our Privacy policy explains.',
         '**The AI makes suggestions, not decisions.** It can misread an amount, a date or a tax. Check every suggestion before you save it. You are responsible for what you save.',
         'Bank feeds bring transactions in through Plaid when you connect a bank. Check them like any other bank line before you add them to the books.']),
 ('h2', '7. Sumlora is a tool, not professional advice'),
 ('ul', ['Sumlora calculates sales tax, payroll deductions and reports from the information you enter, using the rates and rules we have built in. Tax rules change, and your situation may need professional judgment.',
         'You are responsible for checking returns, payroll, slips and reports before you file or rely on them, and for filing them on time with the Canada Revenue Agency, Revenu Québec or any other authority.',
         'If you find an error in a rate or calculation, tell us and we will fix it as soon as we can.']),
 ('h2', '8. Fair use'),
 ('p', 'Don’t use Sumlora to break the law, to store information you have no right to hold, to attack or overload the service, to copy or resell it, or to get into accounts or companies that aren’t yours. We may suspend an account that does, and we will tell you why.'),
 ('h2', '9. Keeping Sumlora running'),
 ('p', 'We work to keep hosted Sumlora available at all times, but we can’t promise it will never be interrupted. We may pause it briefly for updates and maintenance, and will warn you ahead of planned work when we can. We may improve or change features over time; we won’t remove a core feature you pay for without telling you at least 30 days before.'),
 ('h2', '10. Limits on our responsibility'),
 ('ul', ['Sumlora is provided as it is. We don’t promise it is free of errors or right for every purpose.',
         'We are not responsible for indirect losses, such as lost profits, penalties or interest charged by a tax authority because a return or payment was late or wrong, or the cost of fixing records.',
         'Our total responsibility for any claim is limited to the fees you paid us in the 12 months before the claim.',
         'Nothing in these terms limits our responsibility where the law does not allow it, including for intentional or gross fault.']),
 ('h2', '11. Ending the agreement'),
 ('ul', ['You can end it by cancelling (section 3).',
         'We can end it with 30 days’ notice, or right away if you seriously break these terms or don’t pay (section 2).',
         'After it ends, you have [60] days to download your books. We then delete them from our servers, and from our backups within a further [30] days, unless the law requires us to keep something longer.']),
 ('h2', '12. Changes to these terms'),
 ('p', 'We may update these terms. We will tell you by email or in Sumlora at least 30 days before a change applies, and ask you to agree again when you next sign in. If you don’t agree, you can cancel before then.'),
 ('h2', '13. Law and courts'),
 ('p', 'These terms are governed by the laws of Quebec and the federal laws of Canada that apply there. Any dispute goes to the courts of the judicial district of [district], Quebec.'),
 ('h2', '14. Language'),
 ('p', 'The French version of these terms was given to you before you agreed to them. After seeing it, you expressly chose to be bound by this English version, as Quebec’s Charter of the French language allows. Les parties ont expressément exigé que la présente convention soit rédigée en anglais, après avoir pris connaissance de sa version française.'),
 ('h2', '15. Contact'),
 ('p', f'{CO} · {EMAIL} · {ADDR}'),
]

TERMS_FR = [
 ('p', f'Les présentes conditions constituent une entente entre {CO}, une société constituée au Québec (« nous »), et l’entreprise ou le cabinet qui s’abonne à Sumlora (« vous »). En créant un compte ou en utilisant Sumlora, vous les acceptez au nom de votre entreprise. Sumlora est vendu aux entreprises, et non aux consommateurs pour un usage personnel.'),
 ('h2', '1. Votre compte'),
 ('ul', ['Vous devez fournir des renseignements exacts à l’inscription et les tenir à jour.',
         'Vous décidez qui, dans votre entreprise, obtient un accès, et avec quel rôle. Vous êtes responsable de ce que vos utilisateurs font dans Sumlora.',
         f'Gardez les mots de passe confidentiels et utilisez la validation en deux étapes. Avisez-nous immédiatement à {EMAIL} si vous croyez que quelqu’un d’autre a accédé à votre compte.',
         'Quand vous invitez un client à consulter ses propres livres, vous êtes responsable d’inviter la bonne personne.']),
 ('h2', '2. Votre abonnement'),
 ('ul', ['Sumlora est facturé **mensuellement, d’avance**, en dollars canadiens, au prix de votre forfait indiqué à l’inscription. La TPS/TVH et la TVQ s’ajoutent s’il y a lieu.',
         'Votre abonnement se renouvelle chaque mois jusqu’à ce que vous le résiliiez.',
         'Nous pouvons modifier les prix. Nous vous en avertirons au moins 30 jours à l’avance, et le nouveau prix s’appliquera à compter du mois suivant cet avis.',
         'Si un paiement échoue, nous vous en avertirons et réessaierons. S’il demeure impayé après [14] jours, nous pourrons limiter votre compte à la consultation jusqu’au paiement. Vos données ne sont pas supprimées pour défaut de paiement avant la fin de la période prévue à la section 11.']),
 ('h2', '3. Résiliation'),
 ('ul', ['Vous pouvez résilier en tout temps, depuis votre compte ou en nous écrivant. La résiliation prend effet à la fin du mois déjà payé.',
         '[Nous ne remboursons pas les mois partiels.] Vous gardez l’accès complet jusqu’à la fin de ce mois.',
         'Avant ou après la résiliation, téléchargez vos livres avec le dossier de fin d’exercice ou une sauvegarde. La section 11 indique combien de temps nous les conservons.']),
 ('h2', '4. Codes de licence de l’application de bureau'),
 ('p', 'Si vous utilisez Sumlora sur votre propre ordinateur, un code de licence l’active. Un code vaut pour l’entreprise à qui il a été remis. Ne le communiquez pas à l’extérieur de votre entreprise et n’essayez pas de le contourner.'),
 ('h2', '5. Vos données'),
 ('ul', ['**Vos livres vous appartiennent** (ou à votre client, si vous êtes un cabinet qui tient ses livres). Nous n’en sommes pas propriétaires et ne les utilisons que pour vous fournir Sumlora.',
         'Vous pouvez télécharger vos livres en tout temps, avec une sauvegarde ou le dossier de fin d’exercice.',
         'Quand nous hébergeons Sumlora, nous le sauvegardons chaque jour. Gardez tout de même vos propres copies des documents importants : les lois fiscales exigent que vous conserviez vos livres au moins 6 ans.',
         'Notre [[Politique de confidentialité|privacy-fr.html]] explique comment nous traitons les renseignements personnels. Pour les cabinets, l’[[Entente sur les données pour les cabinets|data-agreement-fr.html]] s’applique aussi et fait partie des présentes conditions.']),
 ('h2', '6. Fonctions d’IA et flux bancaires'),
 ('ul', ['Sumlora peut lire les reçus et les factures, et suggérer des catégories pour les lignes bancaires, à l’aide de l’IA Claude d’Anthropic. Ces fonctions sont désactivées jusqu’à ce que vous les activiez pour une entreprise. Une fois activées, ce que vous demandez à l’IA de lire est transmis à Anthropic aux États-Unis, comme l’explique notre Politique de confidentialité.',
         '**L’IA fait des suggestions, pas des décisions.** Elle peut mal lire un montant, une date ou une taxe. Vérifiez chaque suggestion avant de l’enregistrer. Vous êtes responsable de ce que vous enregistrez.',
         'Les flux bancaires importent les opérations par l’intermédiaire de Plaid quand vous connectez une banque. Vérifiez-les comme toute autre ligne bancaire avant de les ajouter aux livres.']),
 ('h2', '7. Sumlora est un outil, pas un conseil professionnel'),
 ('ul', ['Sumlora calcule les taxes de vente, les retenues sur la paie et les rapports à partir des renseignements que vous saisissez, selon les taux et règles que nous y avons intégrés. Les règles fiscales changent, et votre situation peut exiger un jugement professionnel.',
         'Vous êtes responsable de vérifier les déclarations, la paie, les feuillets et les rapports avant de les produire ou de vous y fier, et de les produire à temps auprès de l’Agence du revenu du Canada, de Revenu Québec ou de toute autre autorité.',
         'Si vous trouvez une erreur dans un taux ou un calcul, avisez-nous et nous la corrigerons dès que possible.']),
 ('h2', '8. Utilisation acceptable'),
 ('p', 'N’utilisez pas Sumlora pour enfreindre la loi, conserver des renseignements que vous n’avez pas le droit de détenir, attaquer ou surcharger le service, le copier ou le revendre, ou accéder à des comptes ou à des entreprises qui ne sont pas les vôtres. Nous pouvons suspendre un compte qui le fait, et nous vous dirons pourquoi.'),
 ('h2', '9. Disponibilité de Sumlora'),
 ('p', 'Nous faisons le nécessaire pour que Sumlora hébergé soit disponible en tout temps, mais nous ne pouvons garantir qu’il ne sera jamais interrompu. Nous pouvons l’arrêter brièvement pour des mises à jour et de l’entretien, et vous avertirons des travaux prévus quand c’est possible. Nous pouvons améliorer ou modifier des fonctions; nous ne retirerons pas une fonction essentielle que vous payez sans vous en avertir au moins 30 jours à l’avance.'),
 ('h2', '10. Limites de notre responsabilité'),
 ('ul', ['Sumlora est fourni tel quel. Nous ne garantissons pas qu’il est exempt d’erreurs ni qu’il convient à tout usage.',
         'Nous ne sommes pas responsables des pertes indirectes, comme les profits perdus, les pénalités ou intérêts imposés par une autorité fiscale parce qu’une déclaration ou un paiement était en retard ou erroné, ou le coût de corriger des dossiers.',
         'Notre responsabilité totale pour toute réclamation est limitée aux frais que vous nous avez payés dans les 12 mois précédant la réclamation.',
         'Rien dans les présentes ne limite notre responsabilité lorsque la loi ne le permet pas, notamment en cas de faute intentionnelle ou de faute lourde.']),
 ('h2', '11. Fin de l’entente'),
 ('ul', ['Vous pouvez y mettre fin en résiliant (section 3).',
         'Nous pouvons y mettre fin avec un préavis de 30 jours, ou immédiatement si vous enfreignez gravement les présentes conditions ou ne payez pas (section 2).',
         'Après la fin, vous avez [60] jours pour télécharger vos livres. Nous les supprimons ensuite de nos serveurs, puis de nos sauvegardes dans un délai additionnel de [30] jours, sauf si la loi nous oblige à conserver quelque chose plus longtemps.']),
 ('h2', '12. Modifications des présentes conditions'),
 ('p', 'Nous pouvons mettre à jour ces conditions. Nous vous en avertirons par courriel ou dans Sumlora au moins 30 jours avant l’entrée en vigueur d’une modification, et vous demanderons de les accepter de nouveau à votre prochaine connexion. Si vous n’êtes pas d’accord, vous pouvez résilier avant cette date.'),
 ('h2', '13. Lois applicables et tribunaux'),
 ('p', 'Les présentes conditions sont régies par les lois du Québec et les lois fédérales du Canada qui s’y appliquent. Tout litige relève des tribunaux du district judiciaire de [district], au Québec.'),
 ('h2', '14. Langue'),
 ('p', 'La version française des présentes conditions vous a été remise avant que vous les acceptiez.'),
 ('h2', '15. Pour nous joindre'),
 ('p', f'{CO} · {EMAIL} · {ADDR}'),
]

DPA_EN = [
 ('p', f'This agreement is between {CO} (“we”) and the bookkeeping or accounting firm that uses hosted Sumlora to keep its clients’ books (“the firm”). It forms part of the Terms of service. It sets out how we protect the personal information in the firm’s books, as Quebec’s private-sector privacy law (Law 25) and Canada’s PIPEDA require when a business entrusts personal information to a service provider.'),
 ('h2', '1. Who decides, who serves'),
 ('ul', ['**The firm decides.** The firm, or its clients, decide what personal information goes into Sumlora and why. The firm remains responsible to its clients for it.',
         '**We serve.** We hold and process that information only to provide Sumlora to the firm, and only as these terms and the firm’s instructions say.']),
 ('h2', '2. What we may and may not do'),
 ('ul', ['We use the firm’s information only to provide, secure, back up and support Sumlora for the firm.',
         'We do not sell it, use it for advertising, or use it to train AI models.',
         'We look at the firm’s books only when needed to keep the service running, fix a problem the firm asked us to fix, or meet a legal obligation.',
         'Everyone on our side who can reach the information is bound by confidentiality and has access only to what their work needs.',
         'We do not keep the information after this agreement ends, except as section 7 says.']),
 ('h2', '3. How we protect it'),
 ('table', ['Measure', 'What it does'], [
   ['Storage in Canada', 'Hosted books, attachments and backups are stored in Microsoft Azure’s Canada East region (Quebec City).'],
   ['Encryption', 'Data is encrypted in transit (HTTPS) and at rest (Azure storage encryption).'],
   ['Passwords', 'Stored only in hashed form; 5 wrong passwords lock the account for 15 minutes.'],
   ['Two-step sign-in', 'Required for every user on the hosted service.'],
   ['Roles', 'Each user sees only the companies and features their role allows; a client sees only their own company.'],
   ['Activity log', 'Every change to the books records who made it and when.'],
   ['Backups', 'Daily, with a copy in separate storage in Canada, kept for [30] days.'],
   ['Updates', 'Security fixes are applied promptly.']]),
 ('h2', '4. Service providers we use'),
 ('p', 'We use the service providers listed in our [[Privacy policy|privacy.html]]: Microsoft (Azure hosting, in Canada), Anthropic (AI features, in the United States, only when the firm turns them on for a company), Stripe (online payments, only when the firm turns them on) and Plaid (bank feeds, only for banks the firm connects). Each is bound by a contract that protects the information at least as well as this agreement.'),
 ('p', 'We will tell the firm at least 30 days before we add or replace a service provider that receives the firm’s personal information. The firm may object, and may cancel without penalty if we can’t address its objection.'),
 ('p', 'Before information leaves Quebec, we assess whether it will be adequately protected, as Law 25 requires. We share a summary of those assessments with the firm on request.'),
 ('h2', '5. If there is a breach'),
 ('ul', ['We tell the firm’s main contact **without delay, and within 72 hours** of learning of a confidentiality incident affecting its information.',
         'We tell the firm what happened, what information and which companies are affected, what we have done to limit the harm, and who to contact.',
         'We record the incident in our incident register and help the firm notify its clients, the Commission d’accès à l’information du Québec or the Office of the Privacy Commissioner of Canada where required.']),
 ('h2', '6. Requests from people'),
 ('p', 'If someone asks us to see, correct or delete their information in the firm’s books, we pass the request to the firm within 5 business days and don’t answer it ourselves unless the firm asks us to. Sumlora’s tools (editing records, exports, the year-end package) let the firm answer most requests itself. We help with the rest.'),
 ('h2', '7. When the agreement ends'),
 ('ul', ['The firm has [60] days to download its books and its clients’ books.',
         'We then delete them from our servers, and from our backups within a further [30] days.',
         'We confirm the deletion in writing on request.',
         'We keep only what the law requires us to keep, such as our own billing records, and protect it under this agreement until it is deleted.']),
 ('h2', '8. Checking that we do what we say'),
 ('p', 'Once a year, or after a breach, the firm may ask us for a written summary of our security measures and of any incidents. The firm may ask reasonable questions, and we will answer them within 30 days.'),
 ('h2', '9. Contact'),
 ('p', f'Privacy officer: {NAME}, {CO} · {EMAIL} · {ADDR}'),
]

DPA_FR = [
 ('p', f'La présente entente est conclue entre {CO} (« nous ») et le cabinet de tenue de livres ou de comptabilité qui utilise Sumlora hébergé pour tenir les livres de ses clients (« le cabinet »). Elle fait partie des Conditions d’utilisation. Elle prévoit comment nous protégeons les renseignements personnels contenus dans les livres du cabinet, comme l’exigent la loi québécoise sur la protection des renseignements personnels dans le secteur privé (Loi 25) et la LPRPDE fédérale lorsqu’une entreprise confie des renseignements personnels à un fournisseur de services.'),
 ('h2', '1. Qui décide, qui sert'),
 ('ul', ['**Le cabinet décide.** Le cabinet, ou ses clients, décident quels renseignements personnels vont dans Sumlora et pourquoi. Le cabinet en demeure responsable envers ses clients.',
         '**Nous servons.** Nous détenons et traitons ces renseignements uniquement pour fournir Sumlora au cabinet, et seulement selon les présentes conditions et les instructions du cabinet.']),
 ('h2', '2. Ce que nous pouvons faire et ne pas faire'),
 ('ul', ['Nous utilisons les renseignements du cabinet uniquement pour fournir, protéger, sauvegarder et soutenir Sumlora pour le cabinet.',
         'Nous ne les vendons pas, ne les utilisons pas à des fins publicitaires et ne nous en servons pas pour entraîner des modèles d’IA.',
         'Nous consultons les livres du cabinet seulement lorsque c’est nécessaire pour faire fonctionner le service, régler un problème à la demande du cabinet ou respecter une obligation légale.',
         'Toute personne de notre côté qui peut accéder aux renseignements est tenue à la confidentialité et n’a accès qu’à ce dont son travail a besoin.',
         'Nous ne conservons pas les renseignements après la fin de la présente entente, sauf comme le prévoit la section 7.']),
 ('h2', '3. Comment nous les protégeons'),
 ('table', ['Mesure', 'Ce qu’elle fait'], [
   ['Stockage au Canada', 'Les livres, pièces jointes et sauvegardes hébergés sont conservés dans la région Canada Est de Microsoft Azure (Québec).'],
   ['Chiffrement', 'Les données sont chiffrées en transit (HTTPS) et au repos (chiffrement du stockage Azure).'],
   ['Mots de passe', 'Conservés seulement sous forme hachée; 5 mauvais mots de passe bloquent le compte pendant 15 minutes.'],
   ['Validation en deux étapes', 'Exigée pour chaque utilisateur du service hébergé.'],
   ['Rôles', 'Chaque utilisateur ne voit que les entreprises et fonctions que son rôle permet; un client ne voit que sa propre entreprise.'],
   ['Journal d’activité', 'Chaque modification des livres indique qui l’a faite et quand.'],
   ['Sauvegardes', 'Quotidiennes, avec une copie dans un stockage distinct au Canada, conservées [30] jours.'],
   ['Mises à jour', 'Les correctifs de sécurité sont appliqués rapidement.']]),
 ('h2', '4. Fournisseurs de services que nous utilisons'),
 ('p', 'Nous utilisons les fournisseurs de services indiqués dans notre [[Politique de confidentialité|privacy-fr.html]] : Microsoft (hébergement Azure, au Canada), Anthropic (fonctions d’IA, aux États-Unis, seulement quand le cabinet les active pour une entreprise), Stripe (paiements en ligne, seulement quand le cabinet les active) et Plaid (flux bancaires, seulement pour les banques que le cabinet connecte). Chacun est tenu par un contrat qui protège les renseignements au moins aussi bien que la présente entente.'),
 ('p', 'Nous avertirons le cabinet au moins 30 jours avant d’ajouter ou de remplacer un fournisseur de services qui reçoit les renseignements personnels du cabinet. Le cabinet peut s’y opposer, et peut résilier sans pénalité si nous ne pouvons répondre à son objection.'),
 ('p', 'Avant que des renseignements quittent le Québec, nous évaluons s’ils bénéficieront d’une protection adéquate, comme l’exige la Loi 25. Nous remettons au cabinet, sur demande, un résumé de ces évaluations.'),
 ('h2', '5. En cas d’incident'),
 ('ul', ['Nous avisons la personne-ressource principale du cabinet **sans délai, et dans les 72 heures** suivant la découverte d’un incident de confidentialité touchant ses renseignements.',
         'Nous indiquons au cabinet ce qui s’est passé, quels renseignements et quelles entreprises sont touchés, ce que nous avons fait pour limiter le préjudice, et qui joindre.',
         'Nous inscrivons l’incident dans notre registre des incidents et aidons le cabinet à aviser ses clients, la Commission d’accès à l’information du Québec ou le Commissariat à la protection de la vie privée du Canada au besoin.']),
 ('h2', '6. Demandes des personnes'),
 ('p', 'Si une personne nous demande de consulter, corriger ou supprimer ses renseignements dans les livres du cabinet, nous transmettons la demande au cabinet dans un délai de 5 jours ouvrables et n’y répondons pas nous-mêmes à moins que le cabinet ne le demande. Les outils de Sumlora (modification des dossiers, exportations, dossier de fin d’exercice) permettent au cabinet de répondre lui-même à la plupart des demandes. Nous l’aidons pour le reste.'),
 ('h2', '7. À la fin de l’entente'),
 ('ul', ['Le cabinet a [60] jours pour télécharger ses livres et ceux de ses clients.',
         'Nous les supprimons ensuite de nos serveurs, puis de nos sauvegardes dans un délai additionnel de [30] jours.',
         'Nous confirmons la suppression par écrit sur demande.',
         'Nous ne conservons que ce que la loi nous oblige à garder, comme nos propres dossiers de facturation, et le protégeons selon la présente entente jusqu’à sa suppression.']),
 ('h2', '8. Vérifier que nous faisons ce que nous disons'),
 ('p', 'Une fois par année, ou après un incident, le cabinet peut nous demander un résumé écrit de nos mesures de sécurité et des incidents survenus. Le cabinet peut poser des questions raisonnables, et nous y répondrons dans un délai de 30 jours.'),
 ('h2', '9. Pour nous joindre'),
 ('p', f'Responsable de la protection des renseignements personnels : {NAME}, {CO} · {EMAIL} · {ADDR}'),
]

DOCS = {'en': {'terms': TERMS_EN, 'privacy': PRIVACY_EN, 'dpa': DPA_EN}, 'fr': {'terms': TERMS_FR, 'privacy': PRIVACY_FR, 'dpa': DPA_FR}}
